version: '3.4'

services:
  client:
    container_name: client
    env_file:
      - client/.env.local
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  admin:
    container_name: admin
    build:
      dockerfile: Dockerfile
      context: ./admin
    ports:
      - "3001:3001"
    depends_on:
      - server
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  redis:
    container_name: redis-cache
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --logLevel warning --requirepass dev
    ports:
      - '6379:6379'
    volumes:
      - redis-cache:/data

volumes:
  redis-cache:
    driver: local
  data:
