version: '3.4'

services:
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: