[gin]
port = "8080"
mode = "debug"
origins = [
    "http://sushikame.com",
    "https://sushikame.com",
    "https://booking.sushikame.com",
    "http://localhost",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:8080",
]

[mongo]
uri = "mongodb://mongodb:27017/"
database_name = "dev"

[redis]
address = "redis-cache:6379"
password = "dev"

[auth]
access_token_pubkey = "devmode"
access_token_ttl = 10
refresh_token_pubkey = "devmode"
refresh_token_ttl = 3600
