name: Build Client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: "client/node_modules"
        key: node-modules-${{ hashFiles('client/package.json') }}
    - run: npm ci --omit=dev --ignore-scripts
      working-directory: client
    - run: npm run build --if-present
      working-directory: client
    - run: npm test
      working-directory: client
