name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/www/kame/
            git pull origin main --no-rebase
            cd client/
            npm install
            npm run build
            cd ../server/
            go build -o kame-server .
            pm2 restart all
